name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: mamutalib/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_c0daea1f-6f7b-43a4-bc4f-29a16d5d9036 }}
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: <mamutalib/mamutalib>
